### ISSUE TITLE
Use a different key than `redirect` to store redirect route when using autologin

### ISSUE THREAD

**Issue by PackBjamin** [damienbod/angular-auth-oidc-client#1060]
We experienced anomalous behavior with our localStorage['redirect'] value being "randomly" cleared out. Further investigation found the culprit was the angular-auth-oidc-client code:

auto-login-service.js
```javascript
const STORAGE_KEY = 'redirect';
```
I'm not familiar with the code base. My initial scan only found this usage. But it might be a good idea to use something like a library wide prefix for localStorage, etc. keys? For example:

```javascript
const LIBRARY_KEY_PREFIX = '__autoLoginSvc__';
const STORAGE_KEY = LIBRARY_KEY_PREFIX + 'redirect';
```

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25295 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] auto-login-service.ts uses localStorage['redirect'] (#1060)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25295>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________
From: PackBjamin ***@***.***>
Sent: Friday, April 23, 2021 8:16:07 PM
To: damienbod/angular-auth-oidc-client ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [damienbod/angular-auth-oidc-client] auto-login-service.ts uses localStorage['redirect'] (#1060)


We experienced anomalous behavior with our localStorage['redirect'] value being "randomly" cleared out. Further investigation found the culprit was the angular-auth-oidc-client code:

auto-login-service.js

const STORAGE_KEY = 'redirect';

I'm not familiar with the code base. My initial scan only found this usage. But it might be a good idea to use something like a library wide prefix for localStorage, etc. keys? For example:

const LIBRARY_KEY_PREFIX = '__autoLoginSvc__'
const STORAGE_KEY = LIBRARY_KEY_PREFIX + 'redirect';

-

**Comment by FabianGosebrink** [comment]
Implemented, will be in Release 12.
