### ISSUE TITLE
App fails if IDP does not return refresh token on refresh token request

### ISSUE THREAD

**Issue by andreaslarssen** [damienbod/angular-auth-oidc-client#1095]
**Describe the bug**
If the IDP does not return a refresh token when refreshing a token (refresh token rotation), everything breaks. 

**Expected behavior**
Expected the app to use the existing refresh token.

**Comment by andreaslarssen** [comment]
Like with #1079 and #825, it seems like this package is opinionated on how the IDP should behave beyond what the RFC dictates. It really shouldn't.

**Comment by damienbod** [comment]
If your IDP does not support refresh token rotation for browser based applications, maybe you should not use refresh tokens. Maybe you could consider switching IDP or move to a server rendered application

Greetings Damien

**Comment by andreaslarssen** [comment]
@damienbod that's not an option for me. As far as I can see from the RFC, refresh token rotation is optional.

**Comment by lexey-evergreen** [comment]
@andreaslarssen I was having this same issue, specifically while using AWS Cognito as my authorization server. It turns out that the [BCP for browser-based applications](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps-08#section-8) requires that the authorization server supports refresh token rotation or sender-constrained refresh tokens, the latter of which AFAIK aren't yet supported by modern browsers.

I'm guessing this library assumes that you're using refresh token rotation because it is a current best practice.

Because AWS Cognito doesn't support refresh token rotation, I had to stop using it and switch to a provider that does. It's apparently a new enough concept that even [Okta's implementation is still in early access](https://developer.okta.com/docs/guides/refresh-tokens/refresh-token-rotation/) as of this post's time.

A potential non-BCP-compliant hackaround would be to save the refresh token in session/local storage and overwrite the object returned from the `/token?grant_type=refresh_token` endpoint with itself, but with the same refresh token re-added. This wouldn't be considered refresh token rotation, but it at least makes the library work with an authorization server that doesn't support refresh token rotation.

**Comment by andreaslarssen** [comment]
@lexey-evergreen Yeah, thanks, I ended up doing the save-the-refresh-token-workaround. It's great that refresh token rotation is supported (and you should of course use it if you can), but it doesn't make sense to me that the lib requires it as long as the RFC doesn't require it. I don't have the privilege of switching IDP for the project I'm working on, though they will support refresh token rotation some time in the near future.

Anyways, I'll be switching lib or building my own down the line, but I've got it set up and working for now. Thanks again.

**Comment by damienbod** [comment]
thanks for your answers. I am closing this as a workaround exists and not using refresh token rotation in the browser is not recommended.

Greetings Damien
