### ISSUE TITLE
[HELP] - Identity User LoggedIn somewhere 

### ISSUE THREAD

**Issue by Sudharsan-Narayanasamy** [damienbod/angular-auth-oidc-client#1101]
We use IdentityServer as OpenID and OAuth provider at our organization and many products within the organization use it for authentication purpose. The angular application uses this package with PKCE Code Flow to integrate with IdentityServer and both login/logout works as expected.

One of the requirements we have now is to check if an user is already logged in somewhere (meaning different application with different domain but same IdentityServer) and navigates to the angular application then we have to automatically log him/her into the angular application. We shouldn't prompt for the user to re-enter his/her credentials.

Can you direct me on how to implement this feature ? Any pointers will be of great help.

Thanks,
Sudharsan N.

**Comment by damienbod** [comment]
Hi @Sudharsan-Narayanasamy 

you can do this in a few different ways.

One possible solution is to use the **checkAuthIncludingServer** instead of the checkAuth, this will login if you have a session on the server already. But if you use the offline_access scope, then consent is required as per spec.

Greetings Damien

**Comment by Sudharsan-Narayanasamy** [comment]
Hi @damienbod 
I will give it a try and let you know.
Thank you for getting back.
