### ISSUE TITLE
Silent Renew process doesn't always start with a protected route

### ISSUE THREAD

**Issue by JerrettDavis** [damienbod/angular-auth-oidc-client#1107]
**Describe the bug**
When using `AutoLoginGuard` globally, rather than manually using `CheckAuth` or similar, the silent renew process fails to start until after the user has been reauthenticated at least one time. This leads to the user being redirected to the login page when navigating between secured routes, even after they've previously been authenticated. 

Once the user has been logged in a second time, the silent renew process usually behaves as intended.

**To Reproduce**
First ensure you have setup `AutoLoginGuards` on all routes. Personally, I did something similar to the following:

```typescript
const appRoutes: Routes = [
  {path: '', pathMatch: 'full', redirectTo: 'home'},
  {path: 'unauthorized', component: UnauthorizedComponent},
  {
    path: 'home',
    canActivate: [AutoLoginGuard],
    loadChildren: () => import('./modules/home/home.module').then(m => m.HomeModule)
  }
  {path: '**', component: PageNotFoundComponent},  // Wildcard route for a 404 page
];
```

Also ensure silent renew is setup:

```typescript
export function configureAuth(oidcConfigService: OidcConfigService) {
  return () =>
    oidcConfigService.withConfig({
      stsServer: environment.identity_url,
      redirectUrl: window.location.origin,
      postLogoutRedirectUri: window.location.origin,
      clientId: environment.client_id,
      scope: environment.scope, // must have offline_access scope
      responseType: 'code',
      silentRenew: true,
      useRefreshToken: true,
      logLevel: LogLevel.Debug,
    });
}
```

1. Open the WebApp
2. Clear all site data 
  ![image](https://user-images.githubusercontent.com/2610199/120673188-928fdd00-c458-11eb-81f5-1fe7d175f5ca.png)
3. Refresh the page (which should cause the user to be authenticated)
4. Open the console and notice silent renew is not running
![image](https://user-images.githubusercontent.com/2610199/120673810-22358b80-c459-11eb-8de2-f04df1abd4e2.png)
5. Wait for the login to timeout and then navigate to another secured route. This should force another sign in.
6. Once the second authentication process has completed, you should be able to open the console and see the silent renew running. If the silent renew process does not start, I've had luck with clearing the cache and refreshing multiple times.
![image](https://user-images.githubusercontent.com/2610199/120675373-9e7c9e80-c45a-11eb-8ac4-5bd76ebb7ce9.png)

**Expected behavior**
The silent renew process should always run as soon as the user has been successfully authenticated (and silent renew is enabled).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: All tested chromium-based browsers (Edge and Chrome)
 - Versions: Edge 90.0.818.46, Chrome 91.0.4472.77

**Additional context**

**Comment by eastjie** [comment]
Ich have the similar problem. In the situation, the item "[xxxx]_storageSilentRenewRunning" is not saved in Session Storage. If the item is saved or added, it seems that the token renew process starts again.

**Comment by JerrettDavis** [comment]
@eastjie Can you elaborate on your workaround a bit? It'd help me get a temporary workaround working for my own project, but it might help point to where the issue is cropping up in the library as well.

**Comment by JerrettDavis** [comment]
I've created a sample application to illustrate the issue. You can find the repo here: https://github.com/JerrettDavis/Angular-OIDC-Client-Callback-Silent-Renew-Bug

To test, first serve the application. Open the application in your browser with devtools open. Clear the application data in dev tools and reload the page. Check the console in the devtools. Assuming the authentication kicked off due to the callback workflow, the silent renew will not have started.

**Comment by eastjie** [comment]
@JerrettDavis, I have tried the following things.

Implement my LoginGuard similar as "AutoLoginGuard", but the difference in my LoginGuard is that the this.checkAuthService.checkAuth() always called in concatMap 

 **return this.authStateService.authorized$.pipe(concatMap((isAuthenticatedAlready) => this.checkAuthService.checkAuth(),** 

From the Issue #1115, it will be changed to "switchMap" in version 12. I haven't test in my project.

The second thought is to use "sessionStorage.setItem" to add [xxxx]_storageSilentRenewRunning. Suddenly, the renew process starts, but I wait also for the answer in the issue, I don't think it is the correct workaround for product and have tried only my development to analyse the problem. 

Because I don't understand, why in "checkAuth" always called explicit in AutoLoginGuard twice only for starting renew process. The "_storageSilentRenewRunning" should be added at the first time correctly.

**Comment by FabianGosebrink** [comment]
After some tests we fixed the issue IMHO. We want this to land in V11 to have the fix if people do not want or can update to V12. V12 will come up in the next weeks, we are almost feature complete and concentrate on this currently. @JerrettDavis did some tests with this fix and considered it okay. Thanks.

**Comment by dbrils** [comment]
I'm having a similar issue with v11.6.11 of this library.

Repro steps:
- Make sure you have set the logging to Debug in the configuration for angular-auth-oidc-client
- Authenticate in the application
- Keep refreshing the application a couple of times (on protected routes)
- Wait until your browser refresh immediately refreshes your access token (because it has expired)
- After the successful refresh of the access token it will stop to check the token

<img width="666" alt="Screenshot 2021-06-24 at 09 20 55" src="https://user-images.githubusercontent.com/28647803/123220168-f775aa80-d4cd-11eb-8124-9306e070be7e.png">
<img width="662" alt="Screenshot 2021-06-24 at 09 24 58" src="https://user-images.githubusercontent.com/28647803/123220296-183e0000-d4ce-11eb-919b-1305aa931a15.png">

Afterwards I no longer get the periodic logging checks for the access token.

**Comment by FabianGosebrink** [comment]
We fixed this in V12. We are currently in a testing phase and will release V12 afterwards.

**Comment by dbrils** [comment]
@FabianGosebrink thanks for the fast response 😊 I wasn't sure if it was related, but I'm glad it will be fixed in v12! 😄
