### ISSUE TITLE
id_token nonce validation fails randomly in 12.0.0

### ISSUE THREAD

**Issue by maxgr0** [damienbod/angular-auth-oidc-client#1170]
**Describe the bug**
As there were some issues with the validation of id tokens already here, I think the behaviour is known. I'am using this library at v12.0.0 and Angular 12.1.1. Sometimes, the nonce validation fails as the values don't match. I think probably some kind of regression happened here when going from 11.x to 12.0.0. 
I've logged all tokens on backend-side to check if it's the error of our oidc implementation but that's not the case as tokens with the correct nonce are issued.
Following scenario happens:
- Library asks for a token, get's one back
- Immediately does subsequent requests but validates the first token and fails with an error stating that the nonce is invalid.
- The behaviour is exactly the same as on old issues but after 3-10 requests it works and the user is signed in.
- I've already increased the `maxIdTokenIatOffsetAllowedInSeconds` to 600.

**To Reproduce**
Use https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-auto-login-all-routes with Angular 12 and v12.0.0 of this library.

**Expected behavior**

**Screenshots**
![Screenshot 2021-07-06 at 12 16 11 AM](https://user-images.githubusercontent.com/48564150/124521518-09b9e780-ddf0-11eb-87b2-5558667a5462.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 11.2.3
 - Browser: Tested with Safari & Chrome

**Comment by maxgr0** [comment]
@FabianGosebrink @damienbod any updates on that? I would be more than happy to provide a PR but currently don't really know where to start.
Cheers!🍻

**Comment by dernilz** [comment]
A while ago i had the same problem using Keycloak as OIDC server.

Via [documentation](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#ignorenonceafterrefresh) I stumbled apon this config option:

> ### `ignoreNonceAfterRefresh`
> 
> - Type: boolean
> - Required: false
> 
> A token obtained by using a refresh token normally doesn't contain a nonce value.   
> The library checks it is not there. However some oidc endpoint implementations do send one.   
> Setting ignoreNonceAfterRefresh to true disables the check if a nonce is present.   
> Please note that the nonce value, if present, will not be verified. Default is false.   

and a [comment in the Implementation](https://github.com/damienbod/angular-auth-oidc-client/blob/release_12_0_1/projects/angular-auth-oidc-client/src/lib/validation/token-validation.service.ts#L208-L228) says this:

>   // id_token C9: The value of the nonce Claim MUST be checked to verify that it is the same value as the one
>   // that was sent in the Authentication Request.The Client SHOULD check the nonce value for replay attacks.
>   // The precise method for detecting replay attacks is Client specific.
> 
>   // However the nonce claim SHOULD not be present for the refresh_token grant type
>   // https://bitbucket.org/openid/connect/issues/1025/ambiguity-with-how-nonce-is-handled-on
>   // The current spec is ambiguous and KeyCloak does send it.

Maybe you have the same problem and `ignoreNonceAfterRefresh: true` is a solution.

**Comment by FabianGosebrink** [comment]
Hey I just tried out the sample as described from you and I can not reproduce the issue. What do I need to do to the sample to reproduce the issue?

**Comment by jochenjonc** [comment]
Hey,

I'm having the same issue, but it is very hard to reproduce. It doesn't occur every time and I have the issue with both KeyCloak and Auth0.
I'll try to debug a little bit to see if I can capture the incorrect nonce.

Regards,

Jochen

**Comment by jochenjonc** [comment]
This is an example of authentication with KeyCloak, it took 9 attempts (ping-ping between angular app and KeyCloak), to eventually authenticate.

![image](https://user-images.githubusercontent.com/436379/126139083-d471fff2-2c33-4f9f-acb4-266498b82722.png)

**Comment by jochenjonc** [comment]
I'm not an expert, but can this be the problem it adds the authNonce to the sessionstate before going to KeyCloak/Auth0 and after returning this one is doesn't match with the one returning from KeyCloak/Auth0.

https://github.com/damienbod/angular-auth-oidc-client/blob/de751a09e2a74a8d5ff33c9dcdb90986d88ce39d/projects/angular-auth-oidc-client/src/lib/utils/url/url.service.ts#L242

**Comment by damienbod** [comment]
Hi @jochenjonc This happens when you send 2 authorize requests so one nonce does not match. You should only call the checkAuth once. If you send multiple authorize requests, then you will have a race.

Greetings Damien

**Comment by maxgr0** [comment]
@damienbod this can be the issue definitely, but (for my example) I don't call `checkAuth` explicit as I'am only using the guard which is shipped with the library 🤔

**Comment by jochenjonc** [comment]
@damienbod I also cannot find my second call to checkAuth.

What I see is the following difference between an unsuccessful and a successful login. Just before where my screenshots start an AuthResult was found in both cases.

Unsuccessful:
![image](https://user-images.githubusercontent.com/436379/126152192-44e5ce16-c97f-4d41-9fc9-f7362afd9a3b.png)

Successfull:
![image](https://user-images.githubusercontent.com/436379/126151968-acc9a0f3-4e71-4d20-ad9b-ee9cf66d3f82.png)
 
As you can see when it fails, it seems that it doesn't detect auth data. And because of that, a new nonce is created.

**Comment by FabianGosebrink** [comment]
Can you provide us a sample repo and use a config from our samples? Thanks!

**Comment by jochenjonc** [comment]
@damienbod it is indeed a race condition. 

My default route redirected to a route with an AutoLoginPartialRoutesGuard on it. A successful login depended on what was first the checkAuth that was being called, the one in my AppComponent or the one in the Guard.

I changed my code to use the AutoLoginAllRoutesGuard, because all routes are protected in my case and I could not simulate the issue anymore.

It's just an idea, but logging an error if CheckAuth is called a second time could have helped in finding the issue. Or maybe just some logging that the Guard is triggering the CheckAuth instead of the one in the AppComponent so you can spot the difference a bit better in the console.

**Comment by damienbod** [comment]
@jochenjonc @FabianGosebrink This sounds like a good idea. A debug log would be nice

@FabianGosebrink Good for you?

@jochenjonc Would you like to do a PR?

Greetings Damien

**Comment by FabianGosebrink** [comment]
I don't see a way to count the calls of `checkAuth()` other than having a counter. Counter means a resetting as well, so when should it be set to zero again? Also, the caller can not be specified afaik. 

Basically 

> It's just an idea, but logging an error if CheckAuth is called a second time could have helped in finding the issue.

We do log an error that the token validation failed. Maybe we can more precise here and add something like "did you call the `checkAuth()` method multiple times?".

What do you think?

**Comment by maxgr0** [comment]
@jochenjonc did you managed to find that race condition? 
Cheers!🍻

**Comment by jochenjonc** [comment]
@maxgr0 yes, but it's hard to solve in this library because actually it is caused by 'misusage' of the built-in guards. In my PR I added extra logging so you can see what happens, but the real solution is to pick the [correct guard](https://github.com/damienbod/angular-auth-oidc-client/blob/962e7a9a1dce34b9d41a3dde317d9311da363582/docs/site/angular-auth-oidc-client/docs/documentation/auto-login.md) in combination with or without a manual checkAuth() call.

**Comment by FabianGosebrink** [comment]
Just in addition: The docs link [here](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/auto-login)
