### ISSUE TITLE
Library causes infinite loop after successful authentication

### ISSUE THREAD

**Issue by pavankjadda** [damienbod/angular-auth-oidc-client#1283]
**Describe the bug**
I am trying to use this in my Angular project which is being authenticated through [LabShare](https://a.labshare.org/) (OIDC provider). I configured simple flow based on instructions from the docs. 

- When user goes to application home page, it checks authentication
- If not authenticated, redirects him to LabShare Login page. User can select any one of the provider and login
- After user logging in LabShare redirects him to Application home page
- However in the previous step I see application trying to authenticate again and again, results in infinite loop

**To Reproduce**
1. Go to repository  'https://github.com/pavankjadda/labshare-test' 
2. Clone it and modify the [OIDC config](https://github.com/pavankjadda/labshare-test/blob/main/src/app/auth/auth-config.module.ts#L8) 
3. Run the project using the command `npm run start` and goto https://localhost:4202

**Expected behavior**
Login flow should work as expected

**Desktop (please complete the following information):**
 - OS:  macOS
 - Browser: Chrome
 - Version: 95

**Comment by pavankjadda** [comment]
I initially has `checkAuth()` on app.component.ts and `AutoLoginPartialRoutesGuard` on home page, which may resulted in infinite loop. But after removing `checkAuth()`, I still get infinite loop

**Comment by damienbod** [comment]
Hi @pavankjadda This usually happens when the guard kicks in before the redirect validation logic runs. Check this the callback or redirect URL is not "Guarded" 

Greeings Damien

**Comment by pavankjadda** [comment]
> Hi @pavankjadda This usually happens when the guard kicks in before the redirect validation logic runs. Check this the callback or redirect URL is not "Guarded" 
> 
> 
> 
> Greetings Damien

I am guarding home page and redirect url is also same. Because I want users to login before accessing the webpage.

**Comment by vlad-geiger-msg-systems** [comment]
Hello guys, I have the same issue: redirecting user after successful login to a guarded path. 
It would be awesome if we could fix it within the library.

Currently there is only one "workaround" for this issue: use an unguarded redirect_url and within the redirect_url use a query param for the "source" of where the user came from and handle that accordingly in the app.

Example of redirect url: 
http://localhost:4200/unguarded_route?source=http://localhost:4200/path/to/guarded_route

**Comment by FabianGosebrink** [comment]
Hey @vlad-geiger-msg-systems, basically that is the way the issue is meant to be solved. Basically we have the two guards and the [AutoLoginAllRoutesGuard](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/auto-login#auto-login-when-all-routes-are-guarded) should be there to do this.

**Comment by vlad-geiger-msg-systems** [comment]
yes, you are correct. I am trying that out right now. I need to configure the storage first for it to work.

**Comment by FabianGosebrink** [comment]
You can also leave the storage default if you want. The Guard does not need a special storage.

**Comment by FabianGosebrink** [comment]
This confuses me. Redirecting manually in the subscribe of the checkAuth() should work. no?

**Comment by vlad-geiger-msg-systems** [comment]
yes, it does work but then it overwrites the "redirect" navigation which in some cases(like mine) is not wanted.

The problem is that I don't know the "redirect" value to compute if my navigation is needed or not, but by subscribing to the NavigationEnd event, I could determine the "redirect" value, and compute if my navigation is needed or not.

basically:
- unguarded and unauthorized path "/" -> Show Presentation Page
- unguarded and authorized path "/" -> Self-Navigate to "/dashboard" -> Show DashboardPage
- guarded and authorized path "/something/else" -> oidc redirect -> Show SomethingElse Page
