### ISSUE TITLE
why do we need to set issValidationOff=true when using a common endpoint in Azure ? (is it safe?)

### ISSUE THREAD

**Issue by chrisdot** [damienbod/angular-auth-oidc-client#1298]
Hello,

BTW, very nice lib !!

I'm currently upgrading a project from angular 11 to 12, and as the API seems to have changed (loading a dynamic configuration through HTTP call), I decided to go back to official samples. 
So I set up a demo project based on latest :
- sample-code-flow-auto-login
- sample-code-flow-http-config with latest 

But when running it against an AzureAD, I had always the following error : 
`[Error] <id> - authorizedCallback, token(s) validation failed, resetting. Hash:...`

Finally I looked at the Azure samples, and [found](https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/sample-code-flow-azure-b2c/src/app/auth-config.module.ts#L20) the following comment:
`issValidationOff: true, // this needs to be true if using a common endpoint in Azure`

Can somebody explain why ? Is this safe in that case ?

Additionnaly, I what does exactly [the following additional parameter](https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/sample-code-flow-azure-b2c/src/app/auth-config.module.ts#L23) mean?
```
 customParamsAuthRequest: {
          prompt: 'select_account', // login, consent
        },
```
Thanks

**Comment by damienbod** [comment]
Hi @chrisdot thanks

issValidationOff: true

You should avoid this if possible, this is required when using multiple tenants and you don't know the issuer. With AAD and single tenant, this should be validated. Always validate the iss if possible.

The select_account is set so that with a sign-in, AAD will ask you the choose an account before continuing. I have lots of different aad accounts... You probably don't need this. You can read up on this on the AAD docs.

Greetings Damien

**Comment by chrisdot** [comment]
Thank you!!
