### ISSUE TITLE
[Bug]:  StorageKeys ->authnResult not being stored if we use Cookie Storage Service instead of session storage

### ISSUE THREAD

**Issue by Dhanapathy-Vadivelu** [damienbod/angular-auth-oidc-client#1437]
**What Version of the library are you using?**
 "version": "14.0.0"

**Describe the bug**
Not able to find authnResult  in cookie storage after successful login. But in V11 we were able to get it.

**To Reproduce**

Write a cookie storage service which should implement AbstractSecurityStorage and use this as storage service instead of default session storage service.
below is the sample
![image](https://user-images.githubusercontent.com/105351115/167888805-c346203f-3f65-46da-89c9-1a20fa5c7714.png)

**Expected behavior**
authnResult  should be available in cookie storage so that we can access refresh token from it . 

**Screenshots**

In V11, we can see all data in cookies as below
![image](https://user-images.githubusercontent.com/105351115/167884746-6ba6559a-473e-430d-848e-149168388281.png)

in V14 , not able to find authnResult  as shown below
![image](https://user-images.githubusercontent.com/105351115/167887800-91ce56d0-a065-4392-ab50-62ae672f831b.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser : chrome 
- Version : 101.0.4951.54

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maxs-rose** [comment]
For me using okta for authentication fails because the cookie size eventually gets larger than 4096 bytes so it no longer updates the value in the cookie storage causing the authentication flow to fail. In previous versions, this wasn't an issue as values were stored as separate cookies rather than 1 "large" json object

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Comment by vinichini** [comment]
Sorry about this reopen but I have also this problem and I didn't understand the solution for this if there is any.
From what I read of solutions to storage in cookies instead of session storage I come up with this: 
![appmodule](https://github.com/damienbod/angular-auth-oidc-client/assets/27076150/2a4b55aa-aa90-4a5b-838f-a66e21e18f6c).
But I'm using version 13.1 and instead of "withConfig" I use "withConfigs" putting the oidc config into an array. Following the solutions I found, if I don't put that config in AuthModule.forRoot it throw an error -  Please make sure you add an object with a 'config' property: ....({ config }) instead of ...(config).
I don't even know if that's the problem but I wonder if there is anyway to manipulate the response so it can be in properties instead of an object and can be stored in cookies.
I normally can find the solution by reading lot of documentation but not in this case. I'm on this for a few days so if I can get any help in here I'll be very very thankfull.

**Comment by iroman91** [comment]
If I use cookies for session storage, I experience the same behavior; the authResult is not stored in the cookie. I'm using version 16 of the package.
