### ISSUE TITLE
[Refactoring]: Use Promise for methods that currently returns Observable and immediately complete it

### ISSUE THREAD

**Issue by Stas-tolpekin** [damienbod/angular-auth-oidc-client#1461]
For example, the method _OidcSecurityService.forceRefreshSession()_ returns _Observable_. But this _Observable_ actually does not present any kind of _stream_ of data. To run the logic of this method I should subscribe to this Observable. But I get only one emittion (_next()_ call) before this Observable is complete. Looks like using this method might be more comfortable if it returns Promise. 
It's not about only this method. It's about all methods that return Observables and after a subscription immediately complete it.

**Comment by FabianGosebrink** [comment]
Hey, thanks for the issue. I don't see an advantage in using promises over Observables here. Is it a common technique to use promise if a stream only fires back once?

**Comment by andreaslarssen** [comment]
...on the other hand Angular HttpClient has methods that returns one-off streams. Not making an argument, just curious about the discussion.

**Comment by Stas-tolpekin** [comment]
> ...on the other hand Angular HttpClient has methods that returns one-off streams. Not making an argument, just curious about the discussion.

Difference is that HttpClient’s methods has a parameter that allows to get progress of response downloading. In this case you’ll get each event of a http request as emissions in the observable. 
By other words, httpClient has methods that returns either one-off streams or multiple-emission streams depend on arguments.

**Comment by FabianGosebrink** [comment]
I see the pros and cons about Promises and Observables, without wanting to take part in a discussion here, what is better than the other. Both have their significant use cases and are the correct tool for a job. Well, Angular relies heavily on Observables. I do not think we will switch the API just because a stream only emits one time. I totally get the point, that this feels very promise-ish, but we won't change the API because of this. You can always wrap the methods you need and convert them into a promise if you want. `from`, `firstValueFrom` and `lastValueFrom` operators can help here imho. 

Closing this now, but feel free to leave your opinion, :) I am also curious about the discussion.
