### ISSUE TITLE
[Question]: How to ensure AutoLoginPartialRoutesGuard uses a specified configuration

### ISSUE THREAD

**Issue by dbrils** [damienbod/angular-auth-oidc-client#1468]
**What Version of the library are you using?**
`14.0.0`

**Question**
I've setup two configurations within my application (one for "end-users" and one for "organizations"). Using the `authorize` method I can pass the correct configuration that should be used to authorize the user. in my case I pass in the second configuration. After succesfully login in, the `postLoginRoute` property redirects the user to the appropriate part of the application. However then the `AutoLoginPartialRoutesGuard` guard triggers (same goes for page refreshes) and forces me to authenticate again using the first configuration. 

Is there any way to tell the guard which configuration should be used?

**Comment by FabianGosebrink** [comment]
Currently, there is no way to tell the route guard to use the second config instead of the first one, it just uses the first one in the array. You can switch the configs for now as a workaround. But I think it is manageable to pass data into the route guard to tell it which config to use. You would just have to pass an identifier as ID to choose the correct config. Would that be okay?

**Comment by FabianGosebrink** [comment]
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.
