### ISSUE TITLE
[Bug]: Package version 14.X is not compatible with Angular 13.X

### ISSUE THREAD

**Issue by WizeInge** [damienbod/angular-auth-oidc-client#1484]
**What Version of the library are you using?**
14.1.1 (i try with 14.0.0 to 14.1.1)

**Describe the bug**
When i ng serve, an error appear

**To Reproduce**

1. Install package version 14.1.1 on project with angular 13.X

**Expected behavior**
ng serve launch without error.

**Screenshots**
![Capture d’écran 2022-07-13 à 11 42 00](https://user-images.githubusercontent.com/10169101/178704059-cfa23006-0d25-446b-aa4f-8d75ec90cff6.png)

**Desktop (please complete the following information):**

- OS: Mac os 12.4
- Browser Chrome
- Version 103

**my package.json:**
<img width="368" alt="Capture d’écran 2022-07-13 à 11 52 02" src="https://user-images.githubusercontent.com/10169101/178705591-3dc90eeb-d972-4fab-82ed-c2a94db65ad8.png">

**Edit**
If in fesm2015/angular-auth-oidc-client.mjs, line 4951, i change minVersion to 12.0.0, the serve work. 

Where i can found a version of this package without this minVersion set to 14.0.0 ?

**Comment by myronu** [comment]
We are fine on version 14.0.2 with Angular 13. Version 14.1 and later now appears to require Angular 14.

**Comment by dabbid** [comment]
There's still a compilation problem with an Angular 13 project and lib version 14.0.2, I get some rxjs operators import error (example: `Error: export 'tap' (imported as 'tap$1') was not found in 'rxjs'`) although my rxjs version (6.6.7) is compliant with lib's peer dependencies (`"rxjs": "^6.5.3 || ^7.4.0"`)
Indeed if I look to the generated `fesm2015/angular-auth-oidc-client.mjs` file, I have this at line 6:
```javascript
import { ReplaySubject, from, of, BehaviorSubject, Observable, throwError, timer, Subject, tap as tap$1, catchError as catchError$1, forkJoin, TimeoutError, switchMap as switchMap$1, map as map$1 } from 'rxjs';
```
Importing `tap`, `catchError`, `switchMap` & `map` from rxjs root causes the problem. The weird thing is that we have this line right after:
```javascript
import { map, mergeMap, tap, distinctUntilChanged, take, switchMap, retryWhen, catchError, retry, concatMap, timeout } from 'rxjs/operators';
```
That's why aliases are created in previous line I guess, but I really wonder why we have these operators imported twice. Any thoughts? And any solution that would avoid upgrading angular on my project (not yet planned for now)?

**Comment by dabbid** [comment]
@WizeInge Did you really manage to get your Angular 13 project working with lib version 14.0.2? Don't have you these rxjs operators wrongly imported at the beginning (line 6) of `fesm2015/angular-auth-oidc-client.mjs` file?

**Comment by WizeInge** [comment]
@dabbid I just upgrade my project to Angular 14 and lib version 14.1.4. 

But when i was on Angular 13 and lib version 14.0.2 no problem with RxJs (v7.4.0). 
I import my operator with :
`import { Observable, of, retry, take, tap } from "rxjs";`

**Comment by dabbid** [comment]
Ok maybe it comes from my RxJs version then (6.6.7), I'm going to check, but if it's the case it would mean lib's peer dependencies are badly defined.

**Comment by dabbid** [comment]
Build is ok with rxjs 7.x.x, I then think lib's rxjs peer dependency should rather be `rxjs": "^7.0.0",`
