### ISSUE TITLE
[Bug]: Silent Renew problem with [cannot destructure property 'configId' of configuration null]

### ISSUE THREAD

**Issue by AliHashemie** [damienbod/angular-auth-oidc-client#1536]
**What Version of the library are you using?**
14.1.4

**Describe the bug**
The problem happens with checkAuthIncludingServer and this configurations
![Screenshot 2022-09-15 220232](https://user-images.githubusercontent.com/31801297/190490223-eac59a65-63ed-4ba3-ad27-8b8e391bcdbb.png)

when user came as anonymous, on first renew try I get this error (it raises from timeoutRetryStrategy)
![Screenshot 2022-09-15 220331](https://user-images.githubusercontent.com/31801297/190490597-5eb36f9e-c631-4d60-85a4-3384ef63be75.png)

as I can see its not happening on logged in sessions

also I Tried to remove configId and use without configId but nothing changes

**Comment by vandykej17** [comment]
I am also having this issue.

**Comment by FabianGosebrink** [comment]
Can you provide a sample repo? You can take one of our samples with our config, the values in the configs are not important.

**Comment by vandykej17** [comment]
I am trying to use implicit, silent renew flow. But, I missed the silent-renew.html so the event that "ends" the oidc flow never got triggered. I'm that case, I hit the default 20 second timeout. If I'm not mistaken, this error will happen for any app that is using silent-renew, but does not return within the 20 seconds.

Once I got my stuff setup, I did not see the error anymore, but in theory, I think the bug is still there. I just don't hit the 20 seconds anymore.

**Comment by FabianGosebrink** [comment]
Alright, we will have an eye on this. Closing this for now, as the error is known, but we have to have a look at this. Thanks.

**Comment by stefanocke** [comment]
For me, this error occured on checkAuthIncludingServer,  if the auth server (issuer) was temporarily not available. 
But I guess this is quite the same as @vandykej17 says, since if auth server is not available, we will never reach the refresh.html and run into the 20s timeout as well.
So maybe, error handling for the iframe could be improved to detect early, if the auth server gives http errors or similar.

**Comment by michaelmarcuccio** [comment]
Having the same scenario mentioned by @stefanocke using v16.0.0 with iframe renew for Code Flow w/ PKCE

**Comment by michaelmarcuccio** [comment]
My IDS is sometimes(rarely) rejecting the Iframe renew when using checkAuthIncludingServer at the /connect/token endpoint. The rejection is the following:

Invalid redirect_uri{ redirectUri = https://**********.com, expectedRedirectUri = https://**********.com/silent-renew.html }

I think there may be some sort of issue with the wrong redirectURI being passed during some part of the checkAuthIncludingServer process during a certain scenario (maybe retry or error handling?).

This may be a separate issue that causes the same error reported by @AliHashemie as it ends up being an error in the iframe area that is not handled.
