### ISSUE TITLE
Introducing yarn

### ISSUE THREAD

**Issue by FabianGosebrink** [damienbod/angular-auth-oidc-client#18]
@robisim74 @damienbod how about introducing yarn? Instead of / Beside npm 5?

**Comment by robisim74** [comment]
For devs who use the library is indifferent. About the packages upgrade, the next one will probably when Angular 5 will be released. I created the starter using only npm so that anyone who develops the library can feel free to use what he prefer: the only important thing is to update the packages only when needed and properly, otherwise devs will get installation issues.

**Comment by damienbod** [comment]
complete
