### ISSUE TITLE
OnCheckSessionChanged is always returning true.

### ISSUE THREAD

**Issue by rpulivarthy** [damienbod/angular-auth-oidc-client#183]
I have added OnCheckSessionChanged as explained in one  of your examples. The event gets fired every 3 seconds and always returns true.

 this.oidcSecurityService.onCheckSessionChanged.subscribe(
        (evt) => {
          console.dir(evt);
          console.log('Session Changed');
          this.refreshSession();
        });

What could be the reason. Appreciate the help

**Comment by damienbod** [comment]
Have you made any progress here?, Any logs?

**Comment by rpulivarthy** [comment]
Seems to work fine when both angular and identityserver running on localhost. When running on different ports on the test server identity server is returning login_required error.

**Comment by rpulivarthy** [comment]
Seems to work fine when both angular and identityserver running on localhost. When running on different ports on the test server identity server is returning login_required error. I will send the logs; working on a something else now. Just want to post to see if you have encountered this before.

**Comment by ussamoo** [comment]
I have the same issue, any idea ? 
Thanks

**Comment by ussamoo** [comment]
Solved for me, it was an issue with Cookie  :  need to add Cookie.SameSite = SameSiteMode.None; 

To be more precise the root of my issue is that I was not using the IdentityServer4.AspNetIdentity library for Identity integration. That library adds this line of code now https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/IdentityServerBuilderExtensions.cs#L48 to turn off the SameSite for Aspnet Identity.

Also, since I wasn't overriding the IUserClaimsPrincipalFactory like that library does now, the idsrv cookie was getting named .AspNetCore.Identity.Application because it was using the Aspnet Identity default factory.

With these changes, I now have everything working as it should. 

Hope this Help

**Comment by damienbod** [comment]
@ussamoo Thanks for the answer.
