### ISSUE TITLE
[Question] Refresh user data

### ISSUE THREAD

**Issue by feco93** [damienbod/angular-auth-oidc-client#210]
Hi!

Is there any way to refresh user data during silent renew? It would be nice, if the UI could react to user data changes without refreshing the whole page.

**Comment by damienbod** [comment]
You would need to do this manually. You could use the event onAuthorizationResult
https://github.com/damienbod/angular-auth-oidc-client/blob/master/API_DOCUMENTATION.md#output-onauthorizationresult-eventemitter

**Comment by mscmnc** [comment]
@damienbod, your answer is not valid now because it's deprecated.
But I thin you can assist me with my issue. 
We authenticate through Azure AD, utilizing refresh tokens, and so forth, and everything works fine except for one issue: I can't comprehend how to retrieve the updated user details in real-time if the username or surname has been changed. 
For instance, in our application, we can modify our name which will change the data through graph API  in Azure AD, and upon change, Azure AD promptly returns the updated name. However, the angular-auth-oidc-client's userData continues to display the old data. I've attempted to refresh tokens, forceRefreshSession, but to no luck. It consistently returns the old name, unless I log off and log in again.

Configuration:
silentRenew: true
useRefreshToken: true
autoUserInfo: false
renewUserInfoAfterTokenRenew: true
ignoreNonceAfterRefresh: true

Thank you for you help!
