### ISSUE TITLE
After Upgrading 6.0.0 retreive siging key Error

### ISSUE THREAD

**Issue by ibrahimsen** [damienbod/angular-auth-oidc-client#225]
Hello,

I have been upgrade my oidc client to latest version. After this upgrade my application get crassed while starting.

I'm provide some logs for you. Thank you for your support.

`

Failed to retreive siging key with error: "[object Object]"

push../node_modules/angular-auth-oidc-client/modules/angular-auth-oidc-client.es5.js.OidcSecurityService.handleErrorGetSigningKeys
--

`
![image](https://user-images.githubusercontent.com/2427905/39911362-c8da91b0-5503-11e8-95c3-198f8029e0a5.png)

**Comment by damienbod** [comment]
@ibrahimsen Could you check the request to the jwk in the network tab in the browswer developer tools? The lib loads the well known json file when starting (Now Angular App init). The has the jwt URL. After a login, the client application using this lib GETs the jwt, and validates the tokens. Either 1 of these network calls is going wrong, or the keys are incorrect on the STS. 

Greetings Damien

**Comment by ibrahimsen** [comment]
Hello @damienbod 

I can get valid response from jwks endpoint, you can see as below. Also I can get tokens from sts server,

![image](https://user-images.githubusercontent.com/2427905/39913442-895edd96-550a-11e8-93a7-640f13c69343.png)



`{
	"keys": [{
		"kty": "RSA",
		"use": "sig",
		"kid": "bb5c8fdbdc9f3d8bbb4132b56ade8363",
		"e": "AQAB",
		"n": "some data",
		"alg": "RS256"
	}]
}`

**Comment by damienbod** [comment]
@ibrahimsen Is it getting blocked? Is CORS enabled for this?

**Comment by ibrahimsen** [comment]
I can get .well-known/openid-configuration configuration via application, if CORS enabled for this I could not get  openid-configuration also. I facing this problem after upgrading.

**Comment by ibrahimsen** [comment]
Dear @damienbod 

I found the problem. It's about HttpClientInMemoryWebApiModule. It's angular bug. When close this module, my issue gone.

Thank you for your quick replies.

**Comment by Biblya** [comment]
@damienbod 
 I am also getting same error 'Failed to retreive siging key with error: {}'
Angular Version: 7.2
OIDC version: 10.0.15 (using authorizedImplicitFlowCallback )

I have debugged library code for above issue and found that http jwks uri GET call never gets triggered due to httpclient error but library fails to print the exact error
this.getSigningKeys().subscribe({ }) calls the 'handleErrorGetSigningKeys' but it fails to print exact error due to internal error.
![image](https://user-images.githubusercontent.com/9976130/84402449-0de1f880-ac22-11ea-8104-ff04fa7adb85.png)

However here is the exact httpclient error
ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

More info and fix about httpclient error
https://github.com/angular/angular/issues/20203

Let me know if you could fix this issue in the version I am using.

Thanks.

**Comment by mhagnumdw** [comment]
> Dear @damienbod
> 
> I found the problem. It's about HttpClientInMemoryWebApiModule. It's angular bug. When close this module, my issue gone.
> 
> Thank you for your quick replies.

The post is already old, but currently, anyone who is experiencing login problems and is using `HttpClientInMemoryWebApiModule`, needs to set `passThruUnknownUrl` to `true`. Example:

```ts
HttpClientInMemoryWebApiModule.forRoot(InMemoryDataService, {
  delay: 100,
  apiBase: 'api/',
  passThruUnknownUrl: true,
}),
```
