### ISSUE TITLE
Misunderstanding or issue renewing tokens

### ISSUE THREAD

**Issue by flhaz** [damienbod/angular-auth-oidc-client#227]
Hi,

We are getting an issue using your library in our application.
We probably did wrong but we are not finding any solution with current documentation.

We avoid silent renew because of the HTML page we have to create, the iframe and because of a possible renew issue if token expires in less than the silent renew refreshes it (maybe we could get more information here).

So we are currently doing an explicit refresh using refreshSession() with an Observable.interval in a SsoService, it did the job but it seems to refresh all the app, our services are reloaded, Observable.interval is used once, we consider it as an issue.

Is this normal ?
What did we wrong ? What should do ?
Thank you in advance for your help.

**Comment by flhaz** [comment]
All specifications we found on internet indicate that we should get a new access token when previous one is expired, but this library is checking token ID, is there as reason ?

**Comment by flhaz** [comment]
In runTokenValidation() of  OidcSecurityService, is there a reason to use setTimeout() instead of using an interval function ? There is a debate in our company about this, why are you not using the time left to expiration as time for setTimeout() ? Why does this run every 3 seconds ? Is there a technical reason ?

**Comment by damienbod** [comment]
Hi @flhaz sorry for the slow answer, very busy at te moment. First question:
I check the id_token, because I use this for the authorization view logic in the APP. I set the lifespan of the access_token to something less than the id_token. I also use a refernce token to the access_token, so it has NO expired time in many applications. The client application should not open the access_token, this is only for the server.

So it makes no point checking the access_token expired time. 

Greetings Damien

**Comment by damienbod** [comment]
@flhaz I need to check this, the setTimeout and running every 3 seconds.

**Comment by profet23** [comment]
@flhaz maybe [this response](https://github.com/damienbod/angular-auth-oidc-client/issues/288#issuecomment-432659790) will answer your question?

**Comment by profet23** [comment]
Closing because I think this has been answered.
