### ISSUE TITLE
Change In silent renew since 3.0

### ISSUE THREAD

**Issue by BiLKiNiS** [damienbod/angular-auth-oidc-client#243]
Hi everyone,
Back in november 2017 my team and I were starting to build a angular website that use Identity Server 4 as an sts.
During the search for a way to integrate the two, I stumble upon this package that seems to do exactly what we needed.
Because I wanted to better understand what it doest, I did not use the package directly but the source instead, it worked fined and I regularly updated the source from the repository until the big gap from 3 to 4 where to many file where change and I could not take the risk of something not working anymore.

Since then our website is in production and work fine and I have time do prepare some code cleanup and to use the nugget package instead of the source.
I manage to make it work for Angular 4.4.6 but the silent renew does not seem to work anymore.
There is a new parameter "silent_renew_url" that did not exist before and during the silent renew the sts return the error "Refused to display 'someurl' in a frame because it set 'X-Frame-Options' to 'sameorigin'."

I do not control the sts so making change to it might be difficult. I wanted to know what is the reason of the change for the silent renew, is it because of security issue that the change happen or because of something else.

Knowing that, I will have the arguments to explain why we need some change to the sts configuration

**Comment by damienbod** [comment]
@BiLKiNiS Thanks .
The silent renew was updated so that only the silent renew html was redirected and updated. Before this change, the whole Angular application was getting refreshed. 

To fix your problems, update:

1) You need to create a silent-renew.html

here's an example:
https://github.com/damienbod/IFrameProtectionSPAs/blob/master/SpaClient/wwwroot/silent-renew.html

Then you need to set the renew configurations:

example:
https://github.com/damienbod/IFrameProtectionSPAs/blob/master/SpaClient/angularApp/app/app.module.ts#L76-L77

The silent renew runs per spec in an IFrame. If your STS Server is blocking this, this needs to be allowed for the silent renew to work.

If the Client APP and the STS are deployed on 2 separate domains, the X-Frame-Options Headers needs to be turned off, and the CSP frame ancestors needs to be configured to only allow the client domain in an IFrame. (The X-Frame-Options header can only be used for a same domain)

I have no example of this. 

It is important to do the IFrame protection correctly to protect against click-jacking from other domains. Only the client domain should be allowed in an IFrame so that the silent renew will work.

Hope this helps

Greetings Damien

**Comment by BiLKiNiS** [comment]
thank you for this information, I will try to make the modificaiton to our Identity Server 4 website

**Comment by profet23** [comment]
Can we close this issue?
