### ISSUE TITLE
authorized event: differentiate between user login and silent renew.

### ISSUE THREAD

**Issue by revok** [damienbod/angular-auth-oidc-client#249]
Version: "angular-auth-oidc-client": "^4.1.0",

In my project, I have a few actions which run after the user has successfully logged in. I use the observable isLogged$ for this, which (along with some other stuff) wraps around oidcSecurityService.getIsAuthorized();

Let's say for example that we want to show a welcome message after the user logs in:

```
this._loginEventSub = this.userService.isLoggedIn$
    .filter((x) => !!x) // Only respond to authorized == true.
    .switchMap(() => this.someDialogService.showDialog$)
    .subscribe();
```

The problem with this code is that a successful silent renew also causes the 'authorized' event to be sent out, which means this dialog will pop up every x minutes (if the silent renew works, that is). There also seems to be no way of determining whether the authorization callback was run in silent renew mode. How can I determine that a user has just logged in?

**Comment by wolfhoundjesse** [comment]
I'm populating our store once the user is authorized, and I've been having the same problem with multiple calls to populate the store and redirecting the app. Since we don't have access to the silent renew event, I set a boolean in local storage `from_silent_renew` to false, and my silent renew asset sets this same value to true. It works for now.

**Comment by damienbod** [comment]
To login, you need to call the authorize function. You could save something to local storage and after a successful login, you can use this with the authorize event to display , do the logic.
