### ISSUE TITLE
wso2 Identity Server audience validation failed

### ISSUE THREAD

**Issue by maghibus** [damienbod/angular-auth-oidc-client#264]
Hi,
I am using angular-auth-oidc-client with **wso2 Identity Server 5.3**
I have tried to log the user in.
wso2is put the **aud claim** into an array
`"aud" : [ "s6BhdRkqt3" ]`

so your library give me the following error:
**authorizedCallback incorrect aud**

it is a bug of yours or wso2is?
I could be mistaken, but I believe was a bug of wso2is.
Thank you

**Comment by fahimulhaque** [comment]
Cause of the issue is below line of code
`const result = this.arrayHelperService.arraysEqual(
                dataIdToken.aud,
                aud
            );`

Type of dataIdToken.aud is **OBJECT** where as type of aud is **String** .

So above line of code will always throw false boolean.


Workaround is to change type of dataIdToken.aud to  String.
`const result = this.arrayHelperService.arraysEqual(
                dataIdToken.aud.toString(),
                aud
            );`

This works for me.
Code link - https://github.com/damienbod/angular-auth-oidc-client/blob/master/src/services/oidc.security.validation.ts

**Comment by damienbod** [comment]
@fahimulhaque Thanks for reporting. I need to investigate this, because this works for all many other OIDC providers which are certified. I need to validate if this is a server bug, or if I should add should code which will allow this, as well as aud returned as a string

**Comment by damienbod** [comment]
added support in version 6.0.6
