### ISSUE TITLE
Silent Renew adds a state in the parent history in Firefox

### ISSUE THREAD

**Issue by shambarick** [damienbod/angular-auth-oidc-client#279]
It doesn't seem that the issue #203 has been completely fixed.
I tried different version 6.0.3-6.0.6 and it doesn't work in Firefox.
However it works fine in Chrome.

**Comment by bereachad** [comment]
This issue also happens if you don't navigate off your current page and let the silent renew fire off twice.  Navigation in my application works fine if I only let the token refresh once, but once it fires twice ( as noted by watching the network traffic to see `token-refresh.html` request ) the back button on the browser attempts to take me back to the `token-refresh.html` page. 

This is in Chrome version 69.0.3497.81 , as well as version 68.0.3440.106. This is using library version 6.0.6

**Comment by bereachad** [comment]
Upon further investigation into this, it appears that the oidc server redirect inside the iFrame back to my `token-refresh.html` page is being added to the history state of the browser. Ideally, when the user then clicks "back" in their browser, they aren't aware that the token-refresh.html page was ever loaded. 

To accomplish this, we can keep track of the "previous url" in angular, and then use `history.replaceState(...)` to modify the history state, but the iFrame needs to be destroyed or else the back button will navigate the contents of the iFrame instead of the browser. 

The above situation causes the entire angular application to be loaded in the iFrame that is given the id of `myIFrameForSilentRenew`.

Is it possible to have a change put in place that will destroy the iFrame and recreate it on on successful authorization ? I think that may help with the issue.
