### ISSUE TITLE
TypeError: Cannot read property 'issuer' of undefined

### ISSUE THREAD

**Issue by arunprasathv** [damienbod/angular-auth-oidc-client#295]
Getting below error, when i try to set wellknownendpoints. I dont have issuer set in the configuration. 
```
  const wellKnownEndpoints = new AuthWellKnownEndpoints();
  wellKnownEndpoints.setWellKnownEndpoints(this.oidcConfigService.wellKnownEndpoints);  - this line throws the error. 
```

Error 

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'issuer' of undefined
TypeError: Cannot read property 'issuer' of undefined
    at AuthWellKnownEndpoints.push../node_modules/angular-auth-oidc-client/modules/angular-auth-oidc-client.es5.js.AuthWellKnownEndpoints.setWellKnownEndpoints

**Comment by flts** [comment]
Hi @arunprasathv,

If you look at the console in the Developer Tools of the browser, you will notice that the library has tried to connect to a URL containing the OpenID Discovery config at `<host>/.well-known/openid-configuration`.
This probably points to the wrong url which is why `this.oidcConfigService.wellKnownEndpoints` is null.
