### ISSUE TITLE
Check Session fails to emit if logoff is used in another browser tab. 

### ISSUE THREAD

**Issue by profet23** [damienbod/angular-auth-oidc-client#303]
When using multiple tabs if you use `OidcSecurityService.logoff()` in one tab, the `session_state` is cleared from storage.

The check session heartbeat will fail to emit with an empty `session_state.` So no action can be taken in other open tabs. 

I'll propose a PR with a fix.

**Comment by warrior711** [comment]
I am facing similar kind of issue.
I login in application in one tab and then open new tab and logout the application in that tab .
Expected behavior : If i refresh or navigate in first tab then it should go to login page.
Actual : We are able to navigate and refresh and it is not redirecting to login.

i am using "angular-auth-oidc-client": "^9.0.4",
Can someone please help ?
 let me know if any further information required.

**Comment by Rjitendra** [comment]
Plz post any code for fix this

**Comment by Rjitendra** [comment]
Plz post any code for fix this

**Comment by Rjitendra** [comment]
Plz post any code for fix this

**Comment by severus1990** [comment]
I am using version **10.0.15**. I am having the same logout issue. When l logout in one tab, and how can I subscribe to that event in the other tab, so that I can prevent the user from hitting the endsession url. Please help! I am looking for a solution for couple of day.
