### ISSUE TITLE
authWellKnownEndpoints undefined after upgrade

### ISSUE THREAD

**Issue by kieranjohn** [damienbod/angular-auth-oidc-client#319]
Hi - thanks for a great lib

After upgrading from `2018-08-18 version 6.0.6` i have been getting an error after signing in.

![bug-report](https://user-images.githubusercontent.com/1954155/47191212-acf11700-d391-11e8-8a00-de3af0109761.gif)

**Repro Steps**:
- clone [HWouters/ad-b2c-oidc-angular](https://github.com/HWouters/ad-b2c-oidc-angular)
- upgrade the `angular-auth-oidc-client` from `v6.0.6` (attempted `v6.0.12` & `v7.0.1`)

More Detail
`getSigningKeys: authWellKnownEndpoints is undefined`
only happens on signin - reloading the page has no error

**Comment by profet23** [comment]
@kieranjohn Thanks for the report.  I found the issue.

I have submitted a pull request for a fix (see above).

In the meantime. You can fix this in the https://github.com/HWouters/ad-b2c-oidc-angular project by editing `redirect.component.ts`

and replacing:
```
this.oidcSecurityService.authorizedCallback();
```

with this:
```
this.oidcSecurityService.getIsModuleSetup()
      .pipe(
        filter((isModuleSetup) => isModuleSetup),
        take(1)
      )
      .subscribe(() => {
        this.oidcSecurityService.authorizedCallback();
      });
```

I also noticed in the above project that silent renew is enabled (default) but no url is specified. @damienbod maybe silent renew should be defaulted to off? 

If its left to its default, it will slow down `getIsAuthorized()` calls as that observable will wait for a timeout because the silent renew will never happen without a url.
