### ISSUE TITLE
OidcSecurityService.getToken() only returns authorizationData and not authorizationDataIdToken 

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/angular-auth-oidc-client#48]
Hi Damo,

Im trying out the new angular auth client.

I noticed when using this client ( OidcSecurityService.getToken() )that its not giving me the full access token. Its giving me the authorizationData

baa0badda05ed62ea1b108d7421cf666a00249d5709c4ee50a42b42ce4273162

But it should be giving me the authorizationDataIdToken  like:

"eyJhbGciOiJSUzI1NiIsImtpZCI6ImI1ODllOTg0ZmE0ZjZkNDQ0OTIzZDIzNGY2OTIwYmQ5IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MDA3MTQyMjksImV4cCI6MTUwMDcxNDUyOSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0NDMwNSIsImF1ZCI6ImFuZ.........."

I looked at the securityService but I only see the getToken function hanging off it.

I am I doing this wrong or is the library wrong?

Cheers

**Comment by damienbod** [comment]
Hi @nigel-dewar 
The getToken() returns the full token returned from the STS server. This example is using a reference token to the access_token, which is just a random string. This is more secure, because the access_token never leaves the secure zone, and the lifecycle of the reference token can be controlled

If you want to just the real access_token in the client, your can reconfigure the STS server config for this client.

**Comment by nigel-dewar** [comment]
Hi Damo, Thanks for your reply. The thing is, when I look in chrome session strorage I can see the full token is being stored there, so I'm not really sure how this is more secure?
![image](https://user-images.githubusercontent.com/9402456/28490004-9ad79186-6f13-11e7-88e7-4155474f211e.png)

**Comment by nigel-dewar** [comment]
I see what you mean Thank you. I changed the sts config for the client from Reference to Jwt.

Thanks for your reply.
