### ISSUE TITLE
Question about the support of `code` + PKCE and `id_token token` response options, but not `code id_token` + PKCE

### ISSUE THREAD

**Issue by CoderNumber1** [damienbod/angular-auth-oidc-client#523]
From the [README](https://github.com/damienbod/angular-auth-oidc-client/tree/ff73c914acc24a46d7b82ce59e73176305cb411d#assetsauthclientconfigurationjson):
> At present only the 'code' with PKCE, 'id_token token' or the 'id_token' flows are supported:
>
>`"response_type": ["code" | "id_token token" | "id_token" ]`
>
>> Note the configuration json must have a property stsServer for this to work.

Given that `code` + PKCE is supported, and `id_token token` is supported, is there a particular reason `code id_token` + PKCE is not?

I was looking over #131, and [this comment](https://github.com/damienbod/angular-auth-oidc-client/issues/131#issuecomment-344024047) indicates that `code id_token` flow wasn't, and shouldn't be supported. If not for the PKCE inclusion, that would make perfect sense. However I'm guessing this issue was commented on and closed before the `code` + PKCE support was added, so I was hoping I could get some clarification.

**Comment by fdipuma** [comment]
Any news? I was wondering the same myself. It should be safe to support `code id_token` + PKCE now.

**Comment by CoderNumber1** [comment]
No news yet that I'm aware of.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by damienbod** [comment]
@CoderNumber1  @fdipuma 

The code id_token flow required different validation, and some extra validation, things like the c_hash in the id_token and so on. The code id_token is not better, or worse than the code flow for trusted applications. I have not evaluated if this flow is even safe to use in an SPA, but it is not required because the code flow with PKCE covers this use case. So at present I have no plans to implement this. Hope this makes sense.

Greetings Damien

**Comment by EtienneK** [comment]
Please reconsider adding this as c_hash checks are required for things like OpenBanking UK and FAPI requirements.

**Comment by damienbod** [comment]
@EtienneK Ok let me check up on this can you send me a link to the specs? Will save me time looking for this 

thanks Damien
