### ISSUE TITLE
authorizedCallback incorrect nonce after token refresh

### ISSUE THREAD

**Issue by stefanvitz** [damienbod/angular-auth-oidc-client#592]
i have set up an angular app according to the manual for an code based standard flow.
login works but after token refresh i get an noonce error. autologin was disabled for testing.
i read quite some issues here where a second auth call caused such problems.
this is not the case in my application.

The only network traffic i have after app initialisation:
POST: https://sso-test.XXX.ch/auth/realms/XXX/protocol/openid-connect/token
Status Code: 200
POST: https://sso-test.XXX.ch/auth/realms/XXX/protocol/openid-connect/certs
Status Code: 200

my browser log. after the last line silentRenewHeartBeatCheck stops and i am logged out. 

````
13:31:02.634 Token not expired?: 1583497863000 > 1583497862634  (true) angular-auth-oidc-client.js:392
13:31:05.636 silentRenewHeartBeatCheck
	silentRenewRunning: false
	idToken: true
	_userData.value: true angular-auth-oidc-client.js:392
13:31:05.638 Token not expired?: 1583497863000 > 1583497865638  (false) angular-auth-oidc-client.js:392
13:31:05.639 IsAuthorized: id_token isTokenExpired, start silent renew if active angular-auth-oidc-client.js:392
13:31:05.642 BEGIN refresh session Authorize angular-auth-oidc-client.js:392
13:31:05.644 RefreshSession created. adding myautostate: 15834978656450.95745397824407850.5096576198542185 angular-auth-oidc-client.js:392
13:31:05.646 found refresh code, obtaining new credentials with refresh code angular-auth-oidc-client.js:392
13:31:05.651 https://XXX.ch/auth/realms/XXX/protocol/openid-connect/token hasAuthorizationHeader:  false app-http-interceptor.ts:44:14
13:31:05.740 token refresh response: {"access_token":"eyJhbG...7,"session_state":"3e534619-5e2d-4392-8710-5742e63a003a","scope":"openid email profile"} angular-auth-oidc-client.js:392
13:31:05.741 BEGIN authorized Code Flow Callback, no auth data angular-auth-oidc-client.js:392
13:31:05.741 history clean up inactive angular-auth-oidc-client.js:392
13:31:05.742
Object { access_token: "eyJhb..., session_state: "3e534619-5e2d-4392-8710-5742e63a003a", scope: "openid email profile", state: "15834978656450.95745397824407850.5096576198542185" }
angular-auth-oidc-client.js:392
13:31:05.744 authorizedCallback created, begin token validation angular-auth-oidc-client.js:392
13:31:05.745 jwks_uri: https://XXX.ch/auth/realms/XXX/protocol/openid-connect/certs angular-auth-oidc-client.js:392
13:31:05.746 https://XXX.ch/auth/realms/XXX/protocol/openid-connect/certs hasAuthorizationHeader:  false app-http-interceptor.ts:44:14
13:31:05.781 Validate_id_token_nonce failed, dataIdToken.nonce: N0.020057968930595971583497797197 local_nonce:--RefreshToken-- angular-auth-oidc-client.js:392
13:31:05.781 authorizedCallback incorrect nonce angular-auth-oidc-client.js:379
13:31:05.782 AuthorizedCallback token(s) invalid angular-auth-oidc-client.js:392
13:31:05.783 authorizedCallback, token(s) validation failed, resetting angular-auth-oidc-client.js:379
13:31:05.783 <empty string> angular-auth-oidc-client.js:379
13:31:05.783 getIsAuthorized: false angular-auth-oidc-client.js:392
13:31:05.784 authentication status changed  false oidc.service.ts:70:18
13:31:08.752 silentRenewHeartBeatCheck
	silentRenewRunning: false
	idToken: false
	_userData.value: false`
````

**Comment by stefanvitz** [comment]
if i use the flag `ignore_nonce_after_refresh: true` everything works fine.
i have not found any documentation on that flag.  is it safe to do so?
is it "normal" for nonce to fail after refresh?

**Comment by marcopierobon** [comment]
It is documented in [the api documentation](https://github.com/damienbod/angular-auth-oidc-client/blob/ce687a4934aed9731e62dac0ae0e45f37cb98088/API_DOCUMENTATION.md)


### ignore_nonce_after_refresh
--
519 |  
520 | A token obtained by using a refresh token normally doesn't contain a nonce value. The library checks it is not there. However some oidc endpoint implementations do send one. Setting ignore_nonce_after_refresh to true disables the check if a nonce is present. Please note that the nonce value, if present, will not be verified. Default is false.

**Comment by stefanvitz** [comment]
Thank you for pointing that  out. I will close the issue. But when it is normal that there is no nonce value on refresh and the default is still false this definitely should be mentioned on the configuration example with silent renew on resume.md

**Comment by martijnvanschie** [comment]
I would like to address this issue once more instead of opening a new one.

The description states that the setting ignores the nonce when set to true. Meaning that if its there is will not validate. If its there is will skip it. But is set to true is should validate the nonce.

In the posters example (as is in my situation) the OIDC endpoint does return a nonce. 

`Validate_id_token_nonce failed, dataIdToken.nonce: N0.020057968930595971583497797197 local_nonce:--RefreshToken-- angular-auth-oidc-client.js:392`

The `dataIdToken` returns a nonce and the `local-nonce` is `--RefreshToken--`. So the local value will never match the OIDC token right. The local one is a fixed value it seams.

This means that in theory only `false` works.

Perhaps the name of the setting is not in line with the functionality. The description states `The library checks it is not there.`. So does the setting indicate that the refresh token if validated to NOT contain a nonce?

Regards,
Martijn

**Comment by Angelinsky7** [comment]
@martijnvanschie i think it's because of this 

https://github.com/damienbod/angular-auth-oidc-client/blob/501d0fe82aecf9052d6a48fc7e6ee2c7ab467d74/projects/angular-auth-oidc-client/src/lib/flows/callback-handling/refresh-session-callback-handler.service.ts#L41

i'm maybe (certainly) mistaken but i think that there is no way to actually use `ignoreNonceAfterRefresh: false` with refresh token (without iframe)
