### ISSUE TITLE
Access token verification / encryption

### ISSUE THREAD

**Issue by jScope** [damienbod/angular-auth-oidc-client#598]
Hello,

I'm using Keycloak 9 as my identity provider. All sources tell me that my configured client must be configured as "public" and not "confidential". The last one has a secret.

My Angular app can't hold a secret, that's clear but is the secret required to obtain an access_token from a confidential client?

What is the best practice to verify access tokens at my REST API?

Can someone please give me a short explanation?

**Comment by damienbod** [comment]
An Angular APP is an SPA and cannot use a secret. The access token which the Angular APP gets, as part of the OpenID Connect Code Flow with PKCE, can be used to access the REST API. The rest api must allow this token and validate it. The Rest API itself can use a secret to do introspection with the STS server. This is between the trusted API and the secure token server, nothing to do with the Angular app.

A rest API can be used by trusted clients, or public clients. I would use an API for one or the other but not both. An API which is used by an Angular APP is always a public api. The tokens used for this can only be attained by using an interactive flow, recommended flow is now Open ID Connect Code Flow with PKCE. (no secret because it is public).
