### ISSUE TITLE
(manual) activate silent renew at a later stage?

### ISSUE THREAD

**Issue by vektorschmied** [damienbod/angular-auth-oidc-client#679]
Hello!

I would like to use SilentRenew. But because of the GDPR, I can't set the option at start, because it sets cookies even in an unauthorized state.Hence my question: how can I activate SilentRenew later? 

Hence my question: how can I activate SilentRenew later? Or can I decativate cookies (in the unauthorized state) for SilentRenew without losing the feature?

Thanks and regards

**Comment by OrionDevelopment** [comment]
As far as GDPR is concerned you are free to set cookies which are detrimental to the functioning of the application, and have nothing to do with storing user information, at least that was my last information. Since a user is not logged in, no information about the user can be stored yet.

However I would also like to get a delayed silent_renew since there is currently a bug with it.

**Comment by vektorschmied** [comment]
> However I would also like to get a delayed silent_renew since there is currently a bug with it.

Yes, but not delayed - but triggered manually.

**Comment by OrionDevelopment** [comment]
To be fair, i fixed the bug, by debugging it properly :D In the end it was a documentation issue with missing documentation on the silent renew. But yeah a manual way to start the silent_renew would be nice.

**Comment by vektorschmied** [comment]
Hello damienbod,

please can you explain me, why you close this issue? Is there a fix for the MANUAL ACTIVATION of the silent renew?
Please keep in mind, that the comment from OrionDevelopment isn't related to my case.

Thank you for your response and this awesome library
Flo

**Comment by damienbod** [comment]
Hi @vektorschmied, thanks. Sorry if I misunderstand this. This is my take. This lib does not use cookies and so the issue here is not part of this lib, or something I can fix here. You have 2 options to refresh your session now from version 11. You can use refresh tokens which will not have issues with cookies, or the silent renew using an iframe, which needs this problem to be solved. 

So a switch to refresh tokens could be used to solve this issue. You need to revoke your tokens on logout which is also supported. 

Link to an example:

https://github.com/damienbod/angular-auth-oidc-client/tree/master/projects/sample-code-flow-refresh-tokens

Hope this is correct, if I misundstood something, or you think I could solve the issue here, lets reopen then. Sorry for just closing this without comment.

Hope this helps

Greetings Damien
