### ISSUE TITLE
Silent Renew stops using refresh token when an updated refresh token isn't provided on refresh (falls back to prompt=none).

### ISSUE THREAD

**Issue by jsferrazza** [damienbod/angular-auth-oidc-client#684]
When using **silentRenew** functionality with **use_refresh_token = true**, a new ID_TOKEN and Access Token are retrieved using the refresh token. Some OP's are configured to issue a new/updated refresh token occasionally when using the original refresh token. 

I've observed that if a new/updated refresh token isn't included with the ID_TOKEN and Access Token when the refresh token is used by silent renew, on the following invocation of **silentRenew**, the mechanism falls back to using the authorization endpoint with **prompt=none** instead of previously issued (and potentially still valid) refresh token. 

Should the **silentRenew** mechanism hold onto the existing refresh_token if a new one isn't provided with updated ID_TOKEN and Access Tokens and continue to use it until it is no longer valid? 

Additionally, at the point where the refresh token is no longer valid, **silentRenew** should not attempt (i.e. fall back) to using **prompt=none** and **getIsAuthorized()** should emit false, although some folks might find use for that and perhaps that behavior could be something configurable?

**Comment by damienbod** [comment]
@jsferrazza thanks for reporting. Yes I will add support for this, but you should really configurae the STS  to use the refresh tokens only once. This will be included in version 11. Then when you logout you can revoke the refresh token. We have also seperated the refreh renew so that it no longer fally back to the other renew process.

Greetings Damien

**Comment by jsferrazza** [comment]
@damienbod, thanks! Can you clarify what you mean by _"... you should really configure the STS to use the refresh tokens only once"_? 

The STS I am familiar with allows you to roll a refresh token (which means provide a refresh token back after the refresh token is used at the token endpoint) periodically or with every use of the refresh token at the token endpoint. If I use the refresh token and I receive back an Access and ID_TOKEN but no refresh token, that does not mean the refresh token I just used is expired/invalid and should be discarded (which is what I am seeing right now). Currently, the only way to ensure that refresh tokens are used on silent renew is to ensure that the STS always sends back a new refresh token (which for all intents and purposes a new reference to the exiting "grant").

**Comment by damienbod** [comment]
@jsferrazza 

Here's an example of an IdentityServer4 configuration. What token service do you use and what configuration do you have? 

rolling  a refresh token with every usage would be great.

Using refresh tokens and an SPA is already a bit of a problem because you cannot store the tokens safely in you browser. By using a refresh token which can be only used once, reduces this risk a bit. So everything you use after the refresh token request, the STS should return, ie the id_token, access token and a new refresh token. If the old one is sent again, it will be rejected. Then you also need to revoke the refresh token when you logout as well. This reduces the risk some more. 

Would it be possible for you to configure this, that the refresh token can only be used once? I would prefer not the support your use case, if possible. Does this make sense?

At present, I still recommend using Code Flow with PKCE and silent renew, but as Safari will be blocking this soon, refresh tokens will be the only way to secure SPA in the future, with the present things, specs available. (Or use a backend, not an SPA)

Referesh token config on IdentityServer4
```
new Client
{
	ClientName = "Code Flow Refresh Tokens(Code with PKCE)",
	ClientId = "angularCodeRefreshTokens",

	AccessTokenLifetime = 330,// 330 seconds, default 60 minutes
	IdentityTokenLifetime = 45,

	AllowAccessTokensViaBrowser = true,
	RedirectUris = new List<string>
	{
		"https://localhost:4204",
		"https://localhost:4204/silent-renew.html"
	},
	PostLogoutRedirectUris = new List<string>
	{
		"https://localhost:4204/unauthorized",
		"https://localhost:4204"
	},
	AllowedCorsOrigins = new List<string>
	{
		"https://localhost:4204"
	},

	RequireClientSecret = false,

	AllowedGrantTypes = GrantTypes.Code,
	RequirePkce = true,
	AllowedScopes = { "openid", "profile", "email", "taler_api" },

	AllowOfflineAccess = true,
	RefreshTokenUsage = TokenUsage.OneTimeOnly
 }
```

For info, we have done a maojr update to this in the coming release, which will be released in the next few days. We're are doing some testing, and finished the docs.

Here's the branch with the latest changes:

https://github.com/damienbod/angular-auth-oidc-client/tree/dev-version-11

or the master issue with the progress.

#609

Greetings Damien

**Comment by damienbod** [comment]
Hi @jsferrazza I've decided not the support this. I think that be allowing refresh tokens to be reused in the browser is too dangerous and would leave to insecure applications. Refresh Tokens in the browser is still not the recommended way to do this, but will probably be ready soon. We have full support for this, when the STS servers are ready. To use refresh tokens in the browser, token rotation must be used, and you must have the revocation endpoint implemented, on both the client and the server. Hope this makes sense to you.

Thanks for reporting 

Greetings Damien
