### ISSUE TITLE
Is token validation dependent on current local time.

### ISSUE THREAD

**Issue by mraju2** [damienbod/angular-auth-oidc-client#743]
**Describe the bug**
Actually this is not a bug, I am trying to understand is token validation dependent on local system time. in my application, if I manually change my local system ahead of "iat" claim then the authentication API call is happening in a loop.

**To Reproduce**
Change System local time to the  next hour or the next day or next year

**Expected behavior**
Is there a way to skip iat claim  with local system time,
Even If i increase to  Offset value to big number the issue will occur.
How can i stop the loop call.

**Environment**
Desktop 

**Additional context**

**Comment by GabrielGil** [comment]
Not sure if it is related, but in the changelog for version 11 there's the item: *Id_Token is rejected because of timing issue when server hour is different then client hour*

**Comment by damienbod** [comment]
Hi @mraju2 If you change the local time on your computer, you have set an incorrect time, and the token will be rejected because it was issued to far away from the server issuer time. The lib compares UTC time, not local time, it compares the UTC time of the server with the UTC time of the local client host. It has a default max offset. So if you reset your clock your time is incorrect and the token is correctly rejected, like the OIDC specs define. 

You can deactivate this validation if you want but I would recommend against this.(disable_iat_offset_validation)

You can increase the max offset also if you want. The choice is yours. 

Greetings Damien
