### ISSUE TITLE
Support for Azure B2C multiple policies

### ISSUE THREAD

**Issue by Rasetti** [damienbod/angular-auth-oidc-client#802]
**Is your feature request related to a problem? Please describe.**
Azure B2C supports different user flows by default (signin, signup, password reset, etc.) which require connecting to different sts endpoints to trigger the flow (the user flow / policy name is actually part of the uri).
The problem is that it is currently not possible to change the sts dynamically, based on the action the user needs to perform.

**Describe the solution you'd like**
I'd like to be able to pass the authority parameter to OidcSecurityService.authorize() so I can trigger the different user flows.
This is similar to how msal.js works.

**Describe alternatives you've considered**
I've looked at the Azure B2C sample, and it doesn't seem to include this functionality. No other suitable alternative was found at this stage.

**Comment by mtelbertbiker** [comment]
I have the same issue.   Any status on this?

**Comment by JuanGarciaCarmona** [comment]
Hi there... 

I've been researching about it, I've just found why it happens and also a solution.... And I will by fixing this 'issue' in my current project (logtrip.com, I am migrating user accounts from Identity server 4 to AD B2C)... 

When the user clicks in that "forgot password" link that is being shown in the signup-signin policy is being redirected to the app and it is its responsibility to handle this redirection. 

It is easy to identify this use case because the redirection has a well known error code, which is: 'AADB2C90118' ...

My workaround will consists in something very similar to this:


AppComponent:

```
OnInit(){
 this.router.events.subscribe(e => {
//// LET's go straight to the point....
      if (e instanceof NavigationEnd) {
        if (this.isBrowser) {
            // HINT: this is the best place I've found to handle callbacks and redirections back to an Angular site, before even consider Auth stuff     ;)   So, in our case:
            if (window.location.href.includes('AADB2C90118')) {
            // We have to redirect the user to:
            window.location.assign(
                'https://HereIsYourTenentName.b2clogin.com/HereIsYourTenentName.onmicrosoft.com/oauth2/v2.0/authorize?'
            +'p=B2C_1_reset'   // Your Reset policy (user flow) Name
            + '&client_id=12345678-1234-1234-1234-123456789123'  // Your client ID
            + '&nonce=defaultNonce'
            + '&redirect_uri=https://localhost:4200'   // ;)
            + '&scope=openid' // 
            + '&response_type=id_token&prompt=login');
          } 
         // ...
        }
      }
      if (e instanceof NavigationCancel || e instanceof NavigationError) {
        this.showSpinner = false; // ;)
        return;
      }
    });
    //...
  }
```

That redirection should bring the user to the reset password page... and back to the site once the password has been reset, then the user has to login as usual.

I hope this helps.

**Comment by damienbod** [comment]
linking this

https://github.com/damienbod/angular-auth-oidc-client/issues/835

**Comment by damienbod** [comment]
support for this added in V12

Thanks for reporting

Greetings Damien
