### ISSUE TITLE
Wanted to read 'angular_authWellKnownEndPoints' but nothing was found

### ISSUE THREAD

**Issue by ruby0602** [damienbod/angular-auth-oidc-client#902]
I encounter the problem, angular is v11

**Comment by ruby0602** [comment]
angular is v11

**Comment by ruby0602** [comment]
compling warning: angular-auth-oidc-client@11.2.3" has incorrect peer dependency "tslib@^1.10.0".”

**Comment by sreeragsurendran507** [comment]
Did you get any solution

**Comment by FabianGosebrink** [comment]
Hey, I assume you get this because you have the debug loglevel on. Waht we dont know is: Is your app working? When do you get the error? Please help us to help you. However: I assume further that this comes from this lines here https://github.com/damienbod/angular-auth-oidc-client/blob/main/projects/angular-auth-oidc-client/src/lib/config/auth-well-known.service.ts#L13-L21 which basically means that it tries to read the authWellKnownEndpoints but has found nothing, so it will ask for them from the url. This is not an error and, I assume again, that your app works. Can you confirm?
