### ISSUE TITLE
 v11.2.3 userData$ return empty

### ISSUE THREAD

**Issue by hmheng** [damienbod/angular-auth-oidc-client#910]
**Describe the bug**
Just updated from v10 to v11.2.3, and hits the bug where userdata$ is always return empty/null. Not sure what really went wrong. But use getPayloadFromIdToken is able to retrieve the token payload.

**Expected behavior**
should be able to get the value of userdata from token.

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS
 - Chrome & Edge Chromium
 - latest

**Comment by hmheng** [comment]
I think i managed to resolved it by enabling auto_userInfo.
However, i got another warning "codeFlowCodeRequest incorrect state"

**Comment by FabianGosebrink** [comment]
Hey, is this problem still relevant`? IMHO the state from the callback does not fit the one which is persisted.

**Comment by Ewerton** [comment]
I'am getting the same error. 
Followed [this](https://github.com/damienbod/angular-auth-oidc-client/tree/main/projects/sample-code-flow-refresh-tokens) sample.

The userData$ is always null for me.
What i've tried so far:

- Disabled any http interceptor of the app.
- configured autoUserInfo: true in the config.
- tried to call oidcSecurityService.getConfiguration() and oidcSecurityService.userData$ in the constructor instead of in the ngInit()
- Called the userInfo endpoint manually (it returns the correct user info data).

Any ideas on what else can I try?
