### ISSUE TITLE
Dynamic custom parameters not added to silent-refresh calls

### ISSUE THREAD

**Issue by JoellyR** [damienbod/angular-auth-oidc-client#911]
**Is your feature request related to a problem? Please describe.**

It seems that the way custom parameters are done have been refactored in the current version of the library. The way dynamic custom parameters are done is to pass them as an argument to the login function... while this works correct for the initial call ... it seems like the same custom params are not passed to the silent-renew call. 

**Describe the solution you'd like**

I was thinking that whatever was passed as a custom param to the login function should also be passed in any silent-renew calls that happen.

**Describe alternatives you've considered**

There is other choices you have like passing it during config time etc.. but for me the param is something that has to be passed in at a later time.

**Comment by juanp3053** [comment]
Hello, I'm not sure this is the same feature but it would be great to have the ability to add "Dynamic Custom Parameters" in the forceRefreshSession similar to "authorize". In the version 10 of this library I was able to combine setCustomRequestParameters() and refreshSession() so that my STS server could provide the appropriate access token depending on the custom parameters provided.

Example:
Current
```
this.oidcSecurityService.authorize({ customParams: { myParam: 'Hello World!' }});
```
Desired
```
this.oidcSecurityService.forceRefreshSession({ customParams: { myParam: 'Hello World!' }});
```
Really liking the version 11 of this library, awesome job! Thank you.

**Comment by damienbod** [comment]
Hi @juanp3053 thanks. , this needs to be fixed.

**Comment by JoellyR** [comment]
@damienbod i seen that you added the fix for @juanp3053 comment. (Added ability to use Custom Parameters when calling ForceRefreshSession) in the latest version. But that is on a forceRefreshSession... Will you be fixing my original issue? Which is the ability of having dynamic custom params propagated to the silent refresh requests?

**Comment by juanp3053** [comment]
@JoellyR That was very good timing I would say? :D

**Comment by JoellyR** [comment]
@juanp3053  Oh my god thanks a bunch that is going to save me some major headaches! Lifesaver!
